### ISSUE TITLE
update igg/ime to support ios15 please

### ISSUE THREAD

**Issue by H5GG** [AquaWu/igg#5]
1: fuzzy search is really needed

2: need a dylib for non-jailbreak

3: increase the price for dev/pro users

**Comment by AquaWu** [comment]
https://github.com/H5GG/H5GG
Don't you have your own? Why do you need iGG/iME?

**Comment by AquaWu** [comment]
https://igg-server.herokuapp.com/

**Comment by H5GG** [comment]
> https://igg-server.herokuapp.com/

Great! We will help you promote!

igg/ime's fuzzy search is the best choice and the only choice, every pro/dev user needs it.
could you provide a dylib for non-jailbreak? ( one license, two versions, jb and non-jb )
Would you like to join discord and communicate with us (https://discord.gg/FAs4MH7HMc)
